#!/bin/bash

set -e
set -x

# Directory containing .tar files with the docker images
tar_dir="/mnt/app/container-images"

# Sanity check : Make sure the directory exists
if [ ! -d "$tar_dir" ]; then
  echo "Directory does not exist: $tar_dir"
  exit 1
fi

for tar_file in "$tar_dir"/*.tar; do
    echo "Loading containerd image from: $tar_file"
    k3s ctr images import $tar_file
done
echo "Finished loading containerd images from $tar_dir"

