#!/bin/bash

set -e
set -x

# Directory containing .tar files with the docker images
tar_dir="/mnt/app/container-images"

# Sanity check : Make sure the directory exists
if [ ! -d "$tar_dir" ]; then
  echo "Directory does not exist: $tar_dir"
  exit 1
fi

for tar_file in "$tar_dir"/*.tar; do
    echo "Loading containerd image from: $tar_file"
    k3s ctr images import $tar_file
done
echo "Finished loading containerd images from $tar_dir"

# Copy contents off the disk before unmount
cp -r /mnt/app/tensorrtllm_backend /tensorrtllm_backend
cp /mnt/app/launch_script.sh /
cp -r /mnt/app/engines/ /engines
cp -r /mnt/app/inflight_batcher_llm/ /inflight_batcher_llm
cp -r /mnt/app/model/ /dev/shm/model/
chmod a=rwx -R /dev/shm/
