steps:
# Access the id_github file from Secret Manager, and setup SSH
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    cp known_hosts.github /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --recurse-submodules
  - git@github.com:mithril-security/blindllama-v2.git
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: "gcr.io/cloud-builders/gcloud"
  entrypoint: /bin/bash
  args: ['-c', './lfs_update.sh']
- id: "build-os-disk"
  name: "earthly/earthly:v0.7.23"
  entrypoint: /bin/sh
  args: ["/workspace/build_os_disk_ci.sh"]
- id: "build-dummy-image-with-digest"
  name: "gcr.io/cloud-builders/docker"
  args: 
    [
      "build",
      "-f",
      "mithrilos.Dockerfile",
      "-t",
      "europe-west1-docker.pkg.dev/amd-sev-356012/quickstart-docker-repo/mithrilos-builder-output/mithrilos-builder-output:latest",
      "."
    ]
artifacts:
  objects:
    location: 'gs://example_image_push/mithrilos-0.0.0/'
    paths: ['output/osdisk/*']
images:
# - "europe-west1-docker.pkg.dev/amd-sev-356012/quickstart-docker-repo/mithrilos-builder-output/git-lfs"
- "europe-west1-docker.pkg.dev/amd-sev-356012/quickstart-docker-repo/mithrilos-builder-output/mithrilos-builder-output:latest"
options:
  requestedVerifyOption: VERIFIED
  machineType: 'E2_HIGHCPU_32'
availableSecrets:
  secretManager:
  - versionName: projects/803149688292/secrets/build-secret/versions/latest
    env: 'SSH_KEY'