steps:
- name: gcr.io/cloud-builders/git
  args: ['submodule', 'update', '--init', '--', 'server/k8s-tpm-device-plugin']
- name: gcr.io/cloud-builders/git
  args: ['submodule', 'update', '--init', '--', 'tensorrtllm_backend']
- id: 'mithrilos-build'
  name: 'earthly/earthly:v0.7.2'
  args:
    - -P
    - +mithril-os 
    - --OS_CONFIG=config.yaml
- id: "build"
  name: "earthly/earthly:v0.7.23"
  args:
    - --allow-privileged
    - --artifact
    - +ci-release/* 
    - ./earthly-target/
  env:
    - "HOME=/root"
- name: "gcr.io/cloud-builders/docker"
  args:
    [
      "build",
      "-t",
      "europe-west1-docker.pkg.dev/amd-sev-356012/quickstart-docker-repo/blindllama-server-builder-output:latest",
      "."
    ]
images:
- 'europe-west9-docker.pkg.dev/operation-405916/blindllama-server/mithril-os-slsa:latest'
- "europe-west1-docker.pkg.dev/amd-sev-356012/quickstart-docker-repo/blindllama-server-builder-output:latest"
options:
  requestedVerifyOption: VERIFIED
  machineType: 'N1_HIGHCPU_32' 