steps:
- name: ''gcr.io/cloud-builders/git'
  entrypoint: ['/bin/bash']
  args: 
  - -c
  - | 
    apt update && apt install git-lfs
    curl -s -H "Content-Type: application/json" -H "Authorization: Bearer $(gcloud auth print-access-token)" https://cloudbuild.googleapis.com/v2/projects/amd-sev-356012/locations/europe-west1/connections/blindllama-v2/repositories/mithril-security-blindllama-v2:accessReadToken
    git lfs pull 
- id: "build-os-disk"
  name: "earthly/earthly:v0.7.23"
  entrypoint: /bin/sh
  args: ["/workspace/build_os_disk_ci.sh"]

- id: "build-dummy-image-with-digest"
  name: "gcr.io/cloud-builders/docker"
  args: 
    [
      "build",
      "-f",
      "mithrilos.Dockerfile",
      "-t",
      "europe-west1-docker.pkg.dev/amd-sev-356012/quickstart-docker-repo/mithrilos-builder-output/mithrilos-builder-output:latest",
      "."
    ]
artifacts:
  objects:
    location: 'gs://example_image_push/mithrilos-0.0.0/'
    paths: ['output/osdisk/*']
images:
# - "europe-west1-docker.pkg.dev/amd-sev-356012/quickstart-docker-repo/mithrilos-builder-output/git-lfs"
- "europe-west1-docker.pkg.dev/amd-sev-356012/quickstart-docker-repo/mithrilos-builder-output/mithrilos-builder-output:latest"

options:
  requestedVerifyOption: VERIFIED
  machineType: 'E2_HIGHCPU_32'