# debug mode enables console access via a root user with password "root"
# debug mode is insecure
debug: true
# Whether to install Nvidia drivers in the rootfs (adds 5-10mn to image build time)
nvidiaDriver: true
